stages:
  - build
  - stylecheck
  - tests
  - deploy

build_job:
  stage: build
  script:
    - cd src/cat && make
    - cd ../grep && make
  after_script:
    - bash src/scripts/notify_tg.sh
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

stylecheck_job:
  stage: stylecheck
  script:
    - clang-format --version
    - cd src/cat && clang-format -style=Google -n -Werror *.c *.h
    - cd ../grep && clang-format -style=Google -n -Werror *.c *.h
  after_script:
    - bash src/scripts/notify_tg.sh

tests_job:
  stage: tests
  script:
    - cd src/cat && make test
    - cd ../grep && make test
  after_script:
    - bash src/scripts/notify_tg.sh
  dependencies:
    - build_job
    - stylecheck_job

deploy_job:
  stage: deploy
  script:
    - chmod +x src/scripts/deploy.sh
    - bash src/scripts/deploy.sh
  after_script:
    - bash src/scripts/notify_tg.sh
  when: manual